### ISSUE TITLE
Opaque of AlphaBlendModeTest.gltf has not passed

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#469] opened 2019-01-18 15:33 UTC
I tried to display [AlphaBlendModeTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) in RedGL.

However, Opaque of [AlphaBlendModeTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) has not passed.
[RedGL + AlphaBlendModeTest.gltf result:](https://cx20.github.io/gltf-test/examples/redgl2/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51395964-6d4ced80-1b81-11e9-9e99-90d8ffde418a.png)

[three.js + AlphaBlendModeTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/27f53fcbf46bfb38f9d801ca40338c90cbb7ad82/examples/threejs/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/51396070-aa18e480-1b81-11e9-9cc5-e24ce7f367ba.png)

**Comment by redcamel** [comment] 2019-01-19 04:14
@cx20 
Before this problem is solved, the normal interpretation of the double side must be processed first.
![image](https://user-images.githubusercontent.com/820587/51422098-19c3b980-1bec-11e9-9342-edd71bd77371.png)
If the double side normal problem is resolved, it seems to be solved naturally.

**Comment by redcamel** [comment] 2019-01-21 06:07
@cx20 
![image](https://user-images.githubusercontent.com/820587/51453712-59250e00-1d84-11e9-87ce-1cbbd6c8715d.png)
Currently solved some part.
But I still did not know the reason for the red box part.
Could you give me some advice on this?

**Comment by cx20** [comment] 2019-01-21 15:18
@redcamel I can not advise because of lack of understanding.
@emackey Do you have any advice?

**Comment by emackey** [comment] 2019-01-21 19:48
> ![image](https://user-images.githubusercontent.com/820587/51453712-59250e00-1d84-11e9-87ce-1cbbd6c8715d.png)

In this image, it appears the alpha values are being multipled by the base color image prior to rendering, turning that color black when the alpha is zero.  glTF defines the alpha channel as being completely ignored when `"alphaMode: "OPAQUE"` is set, so the base color should not be multiplied by the alpha channel here.

The same effect can be seen on the blue-and-yellow striped part.  In the above screenshot, you can see the stripes fading away to black as the alpha values become lower.  But in the ThreeJS screenshot at the top of this thread, the stripes remain constant, independent of the alpha values, which is correct for glTF.

As a separate issue, take a look at the middle card, "Cutoff 0.25".  We shouldn't see any marble texture from the background leaking through this card.  glTF's alpha-masking mode is considered opaque, with blending disabled and depth-writes enabled.  It just discards fragments that fall below the cutoff value, but does no other "transparent" type operations.

**Comment by redcamel** [comment] 2019-01-23 12:54
@cx20 @emackey 
I am still working on this problem.
But I will surely solve this problem.

**Comment by redcamel** [comment] 2019-01-24 11:53
### Current research situation.
- resolved blend and mask.
![image](https://user-images.githubusercontent.com/820587/51676111-031cc880-2019-11e9-82a1-16ba4383edce.png)

- but opaque mode  is not yet.
It may be because the primitives tangent has not yet been parsed.
it will be fixed soon.
![image](https://user-images.githubusercontent.com/820587/51676372-c8676000-2019-11e9-9ca8-1f7735bf5e4c.png)


![image](https://user-images.githubusercontent.com/820587/51676224-555de980-2019-11e9-995e-fb71c6fd33ab.png)

**Comment by emackey** [comment] 2019-01-24 21:47
I haven't looked at your code, but I don't think the tangent vectors would be the problem here.  The most unusual thing about that checkbox is that the texture there intentionally has all zeros for the alpha channel, to test if the engine will discard zero-alpha fragments in opaque mode (which it should not).  In the screenshot, they're not being discarded, but they are turning black, probably as a result of being multiplied by zero someplace.

**Comment by redcamel** [comment] 2019-01-26 06:19
@emackey @cx20 
As you said, it has nothing to do with tangents.
and so checked Texcoord. move the uv.y value slowly over time, the texture color is output correctly. 
so I suspect that there is a problem with uv parsing.
But currently I can not find any problem. ㅠ_ㅠ
It will take more time maybe resolve this problem.

Are there any problems you anticipate?

origin
![image](https://user-images.githubusercontent.com/820587/51783459-6a538d80-217d-11e9-9690-7a90a1c39521.png)

time base move texcoord.y
![image](https://user-images.githubusercontent.com/820587/51783467-82c3a800-217d-11e9-852f-de70b8a26d8e.png)

**Comment by cx20** [comment] 2019-01-29 15:03
The following is additional test data.
https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Material_AlphaBlend
https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Material_AlphaMask

Some seem to be different from assumed results.
If you clear these tests one by one, I think that the problem of AlphaBlendModeTest.gltf will be solved as well.

**Comment by redcamel** [comment] 2019-02-05 07:39
@cx20 
### RnD Result
![image](https://user-images.githubusercontent.com/820587/52258667-50772f00-2963-11e9-90db-b6c67d1c14c3.png)
Finally found the cause.
This is because we used window.createImageBitmap.
RedGL supports 'OffscreenCanvas'. So I load the image via window.createImageBitmap. However, 'premultiply' is enforced at when use window.createImageBitmap. 

There is an option in the MDN document not to run premultiplyAlpha, but it is inferred that it does not work as intended.
![image](https://user-images.githubusercontent.com/820587/52258897-1eb29800-2964-11e9-8153-dd6a4e842b2a.png)

I will decide on this part and update it soon.

**Comment by emackey** [comment] 2019-02-05 14:18
Looks great!

**Comment by cx20** [comment] 2019-02-05 15:18
@redcamel I confirmed that the problem was solved with the latest version of the library.

[RedGL + AlphaBlendModeTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/56a1a9187898cc874ff188e6504299a38b232762/examples/redgl2/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52282764-7a047a80-29a4-11e9-9a43-37238509d223.png)

I updated the status of RedGL in [gltf-test](https://github.com/cx20/gltf-test#feature-test-models).
![image](https://user-images.githubusercontent.com/1833979/52282843-a28c7480-29a4-11e9-8beb-84421856dd0e.png)

**Closed** 2019-02-06 01:55 UTC
Labels: bug, dev
